name = "cf_ai_workers_ai_chat"
main = "src/index.ts"
compatibility_date = "2024-09-22"

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

workers_dev = true

[assets]
directory = "public"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "ConversationDO"
class_name = "ConversationDO"

[[migrations]]
tag = "v1"
new_classes = ["ConversationDO"]

[
vars
]
MODEL = "@cf/meta/llama-3.3-70b-instruct"


